version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo_notes

  todo_notes:
    build: ./todo_notes
    privileged: true
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    command: bash -c "
      python manage.py migrate &&
      gunicorn todo_notes.wsgi -b 0.0.0.0:8080
      "
    environment:
      DJANGO_SETTINGS_MODULE: "todo_notes.settings.prod"

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - todo_notes

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx